import type { CollectionPack } from './types.ts';

export const COZY_CATS_PACK = {
  collection: {
    id: 'cozy-cats',
    name: 'The Nook Neighbors',
    description:
      'The friendly cats who make Number Nook feel like home, from sunny reading corners to starry rooftop hideaways.',
    sortOrder: 10,
  },
  collectibles: [
    {
      id: 'cozy-cats:sunny',
      collectionId: 'cozy-cats',
      name: 'Sunny',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A warm-hearted cat who always spots the bright side.',
      art: {
        classic: 'collectibles/sunny.svg',
        sticker: 'collectibles/sunny-sticker.webp',
      },
      theme: {
        accent: '#A94712',
        accentStrong: '#78300D',
        accentSoft: '#FFF0D2',
        pageTint: '#FFF9EE',
        glowPrimary: '#FFE1A8',
        glowSecondary: '#F1E4FF',
      },
      altText: 'A cheerful golden cat with a sun-shaped charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: true,
      sortOrder: 10,
    },
    {
      id: 'cozy-cats:moonbeam',
      collectionId: 'cozy-cats',
      name: 'Moonbeam',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A dreamy night owl who loves quiet puzzles.',
      art: {
        classic: 'collectibles/moonbeam.svg',
        sticker: 'collectibles/moonbeam-sticker.webp',
      },
      theme: {
        accent: '#5C3DF5',
        accentStrong: '#3F25CC',
        accentSoft: '#EEEAFF',
        pageTint: '#FFF8EE',
        glowPrimary: '#EEE7FF',
        glowSecondary: '#FFE6C7',
      },
      altText: 'A lavender cat with a crescent moon charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: true,
      sortOrder: 50,
    },
    {
      id: 'cozy-cats:pepper',
      collectionId: 'cozy-cats',
      name: 'Pepper',
      species: 'cat',
      specialGuest: false,
      rarity: 'rare',
      description: 'A bold little explorer who never gives up.',
      art: {
        classic: 'collectibles/pepper.svg',
        sticker: 'collectibles/pepper-sticker.webp',
      },
      theme: {
        accent: '#A92F49',
        accentStrong: '#742039',
        accentSoft: '#FFE5E8',
        pageTint: '#FFF8F3',
        glowPrimary: '#FFD4DB',
        glowSecondary: '#EADFF8',
      },
      altText: 'A charcoal cat with a coral scarf.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: true,
      sortOrder: 80,
    },
    {
      id: 'cozy-cats:cloud',
      collectionId: 'cozy-cats',
      name: 'Cloud',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A soft, bouncy cat who makes hard days lighter.',
      art: {
        classic: 'collectibles/cloud.svg',
        sticker: 'collectibles/cloud-sticker.webp',
      },
      theme: {
        accent: '#286BA6',
        accentStrong: '#194B78',
        accentSoft: '#E5F3FF',
        pageTint: '#F8FCFF',
        glowPrimary: '#D8F0FF',
        glowSecondary: '#EEE7FF',
      },
      altText: 'A fluffy white cat with sky-blue markings.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 20,
    },
    {
      id: 'cozy-cats:comet',
      collectionId: 'cozy-cats',
      name: 'Comet',
      species: 'cat',
      specialGuest: false,
      rarity: 'legendary',
      description: 'A cosmic cat who races answers across the stars.',
      art: {
        classic: 'collectibles/comet.svg',
        sticker: 'collectibles/comet-sticker.webp',
      },
      theme: {
        accent: '#4055C8',
        accentStrong: '#293892',
        accentSoft: '#E8ECFF',
        pageTint: '#FAF9FF',
        glowPrimary: '#DCE5FF',
        glowSecondary: '#EBDFFF',
      },
      altText: 'A deep blue cat with a glowing comet tail.',
      capsuleEligible: true,
      capsuleWeight: 4,
      shopEligible: true,
      shopPrice: 840,
      starterEligible: false,
      sortOrder: 100,
    },
    {
      id: 'cozy-cats:biscuit',
      collectionId: 'cozy-cats',
      name: 'Biscuit',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A cheerful baker who believes every problem is easier with a warm snack.',
      art: {
        classic: 'collectibles/biscuit.svg',
        sticker: 'collectibles/biscuit-sticker.webp',
      },
      theme: {
        accent: '#9A4F28',
        accentStrong: '#683216',
        accentSoft: '#F9E3C5',
        pageTint: '#FFF9EF',
        glowPrimary: '#F5D2A8',
        glowSecondary: '#F2E4FF',
      },
      altText: 'A round biscuit-beige cat with cinnamon freckles and a biscuit medallion.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 30,
    },
    {
      id: 'cozy-cats:juniper',
      collectionId: 'cozy-cats',
      name: 'Juniper',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A patient plant keeper who knows that small progress grows into big things.',
      art: {
        classic: 'collectibles/juniper.svg',
        sticker: 'collectibles/juniper-sticker.webp',
      },
      theme: {
        accent: '#397A47',
        accentStrong: '#22532E',
        accentSoft: '#E5F3DF',
        pageTint: '#FBFCF5',
        glowPrimary: '#D9EECF',
        glowSecondary: '#FFE4CB',
      },
      altText: 'A patient brown tabby cat with green eyes and a leafy sprig.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 40,
    },
    {
      id: 'cozy-cats:patches',
      collectionId: 'cozy-cats',
      name: 'Patches',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A curious artist who turns every mistake into part of the picture.',
      art: {
        classic: 'collectibles/patches.svg',
        sticker: 'collectibles/patches-sticker.webp',
      },
      theme: {
        accent: '#B2435A',
        accentStrong: '#792C40',
        accentSoft: '#FFE4E9',
        pageTint: '#FFF9F6',
        glowPrimary: '#FFD3DC',
        glowSecondary: '#DDF2ED',
      },
      altText:
        'A playful calico cat with teal eyes, a coral neckerchief, and colorful paint marks.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 60,
    },
    {
      id: 'cozy-cats:gizmo',
      collectionId: 'cozy-cats',
      name: 'Gizmo',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'An inventive tinkerer who loves finding more than one way to solve a problem.',
      art: {
        classic: 'collectibles/gizmo.svg',
        sticker: 'collectibles/gizmo-sticker.webp',
      },
      theme: {
        accent: '#187887',
        accentStrong: '#0D505B',
        accentSoft: '#DEF3F5',
        pageTint: '#F8FCFC',
        glowPrimary: '#D1EEF0',
        glowSecondary: '#F2DFC4',
      },
      altText: 'A blue-gray tinkering cat with teal eyes, copper goggles, and a gear charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 70,
    },
    {
      id: 'cozy-cats:aurora',
      collectionId: 'cozy-cats',
      name: 'Aurora',
      species: 'cat',
      specialGuest: false,
      rarity: 'rare',
      description: 'A radiant sky painter who leaves ribbons of color wherever curiosity leads.',
      art: {
        classic: 'collectibles/aurora.svg',
        sticker: 'collectibles/aurora-sticker.webp',
      },
      theme: {
        accent: '#6C45B5',
        accentStrong: '#493080',
        accentSoft: '#F0E8FF',
        pageTint: '#FFF9FC',
        glowPrimary: '#DDF1E9',
        glowSecondary: '#F4D9F0',
      },
      altText: 'A pearly cat with violet eyes, a colorful aurora marking, and a prism charm.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 90,
    },
  ],
} as const satisfies CollectionPack;
