import type { CollectionPack } from './types.ts';

export const GARDEN_WINGLETS_PACK = {
  collection: {
    id: 'garden-winglets',
    name: 'Garden Winglets',
    description:
      'Ten bright little birds who make every corner of their community garden sing, bloom, and sparkle.',
    sortOrder: 40,
  },
  collectibles: [
    {
      id: 'garden-winglets:tuck',
      collectionId: 'garden-winglets',
      name: 'Tuck',
      species: 'bird',
      specialGuest: false,
      rarity: 'common',
      description:
        'A nimble white-breasted nuthatch who tucks bright ideas into every little nook.',
      art: {
        classic: 'collectibles/tuck.svg',
        sticker: 'collectibles/tuck-sticker.webp',
      },
      theme: {
        accent: '#7A4A24',
        accentStrong: '#4B2C15',
        accentSoft: '#F4E4D2',
        pageTint: '#FFF9F1',
        glowPrimary: '#E9CFAD',
        glowSecondary: '#DCEBDD',
      },
      altText:
        'A white-breasted nuthatch with a black cap and blue-gray wings climbing headfirst down a birch trunk.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 310,
    },
    {
      id: 'garden-winglets:marigold',
      collectionId: 'garden-winglets',
      name: 'Marigold',
      species: 'bird',
      specialGuest: false,
      rarity: 'common',
      description: 'A sunny goldfinch whose morning songs seem to wake the flowers.',
      art: {
        classic: 'collectibles/marigold.svg',
        sticker: 'collectibles/marigold-sticker.webp',
      },
      theme: {
        accent: '#8A5900',
        accentStrong: '#563600',
        accentSoft: '#FFF0B8',
        pageTint: '#FFFCED',
        glowPrimary: '#FFE08A',
        glowSecondary: '#F5D8E2',
      },
      altText: 'A bright yellow American goldfinch with black wings and a marigold charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 320,
    },
    {
      id: 'garden-winglets:bluebell',
      collectionId: 'garden-winglets',
      name: 'Bluebell',
      species: 'bird',
      specialGuest: false,
      rarity: 'common',
      description: 'A clever blue jay who remembers every seed, acorn, and secret garden corner.',
      art: {
        classic: 'collectibles/bluebell.svg',
        sticker: 'collectibles/bluebell-sticker.webp',
      },
      theme: {
        accent: '#24658A',
        accentStrong: '#153F59',
        accentSoft: '#DDEFF7',
        pageTint: '#F8FCFB',
        glowPrimary: '#C9E7F3',
        glowSecondary: '#E3E8BC',
      },
      altText: 'A blue jay with a swept crest, black necklace, barred wings, and bluebell charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 330,
    },
    {
      id: 'garden-winglets:tumble',
      collectionId: 'garden-winglets',
      name: 'Tumble',
      species: 'bird',
      specialGuest: false,
      rarity: 'common',
      description:
        'A tiny bobwhite quail who pats winding garden paths smooth with quick little steps.',
      art: {
        classic: 'collectibles/tumble.svg',
        sticker: 'collectibles/tumble-sticker.webp',
      },
      theme: {
        accent: '#75502E',
        accentStrong: '#49301B',
        accentSoft: '#F1E3D0',
        pageTint: '#FCFAF2',
        glowPrimary: '#E6CDAA',
        glowSecondary: '#D9E6C8',
      },
      altText: 'A plump northern bobwhite quail with a striped face and stepping-stone charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 340,
    },
    {
      id: 'garden-winglets:zinnia',
      collectionId: 'garden-winglets',
      name: 'Zinnia',
      species: 'bird',
      specialGuest: false,
      rarity: 'uncommon',
      description:
        'A swift ruby-throated hummingbird who carries friendly news from flower to flower.',
      art: {
        classic: 'collectibles/zinnia.svg',
        sticker: 'collectibles/zinnia-sticker.webp',
      },
      theme: {
        accent: '#963B6B',
        accentStrong: '#5D2342',
        accentSoft: '#F7DFEB',
        pageTint: '#FFF9FB',
        glowPrimary: '#F0C5DC',
        glowSecondary: '#CFE9E2',
      },
      altText: 'A tiny green hummingbird with a ruby throat beside a bright zinnia blossom.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 350,
    },
    {
      id: 'garden-winglets:bramble',
      collectionId: 'garden-winglets',
      name: 'Bramble',
      species: 'bird',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A bright cardinal who knows exactly where the sweetest garden berries grow.',
      art: {
        classic: 'collectibles/bramble.svg',
        sticker: 'collectibles/bramble-sticker.webp',
      },
      theme: {
        accent: '#8C3B32',
        accentStrong: '#57231E',
        accentSoft: '#F7E0DC',
        pageTint: '#FFF9F3',
        glowPrimary: '#EFC8BF',
        glowSecondary: '#D9E7CE',
      },
      altText: 'A red northern cardinal with a pointed crest, dark face, and berry-vine charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 360,
    },
    {
      id: 'garden-winglets:fern',
      collectionId: 'garden-winglets',
      name: 'Fern',
      species: 'bird',
      specialGuest: false,
      rarity: 'uncommon',
      description:
        'A curious Carolina wren who inspects every vine, trellis, and hidden garden nook.',
      art: {
        classic: 'collectibles/fern.svg',
        sticker: 'collectibles/fern-sticker.webp',
      },
      theme: {
        accent: '#32704B',
        accentStrong: '#1E4930',
        accentSoft: '#DFF0E4',
        pageTint: '#F9FCF5',
        glowPrimary: '#CBE5D0',
        glowSecondary: '#E8D8A9',
      },
      altText:
        'A warm brown Carolina wren with a white eyebrow, upright tail, and curled vine charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 370,
    },
    {
      id: 'garden-winglets:tempo',
      collectionId: 'garden-winglets',
      name: 'Tempo',
      species: 'bird',
      specialGuest: false,
      rarity: 'rare',
      description: 'A lively red-bellied woodpecker who taps out rhythms for the whole garden.',
      art: {
        classic: 'collectibles/tempo.svg',
        sticker: 'collectibles/tempo-sticker.webp',
      },
      theme: {
        accent: '#55409C',
        accentStrong: '#332568',
        accentSoft: '#E9E3FA',
        pageTint: '#FBF9FF',
        glowPrimary: '#D8CCF5',
        glowSecondary: '#F4D9B8',
      },
      altText:
        'A red-bellied woodpecker with a red crown and black-and-white barred wings drumming on a garden post.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 380,
    },
    {
      id: 'garden-winglets:prism',
      collectionId: 'garden-winglets',
      name: 'Prism',
      species: 'bird',
      specialGuest: false,
      rarity: 'rare',
      description:
        'A watchful belted kingfisher who spots tiny rainbows hiding in the garden pond.',
      art: {
        classic: 'collectibles/prism.svg',
        sticker: 'collectibles/prism-sticker.webp',
      },
      theme: {
        accent: '#176B72',
        accentStrong: '#0E444A',
        accentSoft: '#D8F0EE',
        pageTint: '#F7FCFB',
        glowPrimary: '#BFE5E3',
        glowSecondary: '#F4D39F',
      },
      altText:
        'A blue-gray belted kingfisher with a shaggy crest, long beak, and rainbow water ring.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 390,
    },
    {
      id: 'garden-winglets:solstice',
      collectionId: 'garden-winglets',
      name: 'Solstice',
      species: 'bird',
      specialGuest: false,
      rarity: 'legendary',
      description: 'A radiant painted bunting whose colorful flight welcomes every new season.',
      art: {
        classic: 'collectibles/solstice.svg',
        sticker: 'collectibles/solstice-sticker.webp',
      },
      theme: {
        accent: '#8A4B00',
        accentStrong: '#542D00',
        accentSoft: '#FCE8B8',
        pageTint: '#FFFAED',
        glowPrimary: '#F7CE76',
        glowSecondary: '#D8D3F2',
      },
      altText: 'A radiant painted bunting with blue, red, green, and gold plumage and a sun charm.',
      capsuleEligible: true,
      capsuleWeight: 4,
      shopEligible: true,
      shopPrice: 840,
      starterEligible: false,
      sortOrder: 399,
    },
  ],
} as const satisfies CollectionPack;
