import type { CollectionPack } from './types.ts';

export const LANTERN_LANE_CATS_PACK = {
  collection: {
    id: 'lantern-lane-cats',
    name: 'Lantern Lane Cats',
    description:
      'Ten evening neighbors who fill a winding little lane with warm windows, bright ideas, and welcoming lights.',
    sortOrder: 30,
  },
  collectibles: [
    {
      id: 'lantern-lane-cats:crumpet',
      collectionId: 'lantern-lane-cats',
      name: 'Crumpet',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A café-window regular who always saves the warmest seat for a friend.',
      art: {
        classic: 'collectibles/crumpet.svg',
        sticker: 'collectibles/crumpet-sticker.webp',
      },
      theme: {
        accent: '#95551A',
        accentStrong: '#60340C',
        accentSoft: '#FCE8C8',
        pageTint: '#FFF9F0',
        glowPrimary: '#F5D39D',
        glowSecondary: '#D7EBE6',
      },
      altText: 'A round cream tabby cat with a teal scarf and a steaming cup charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 210,
    },
    {
      id: 'lantern-lane-cats:tansy',
      collectionId: 'lantern-lane-cats',
      name: 'Tansy',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A cheerful florist who tucks a little color into every corner of the lane.',
      art: {
        classic: 'collectibles/tansy.svg',
        sticker: 'collectibles/tansy-sticker.webp',
      },
      theme: {
        accent: '#A4453C',
        accentStrong: '#6B2824',
        accentSoft: '#FBE3DE',
        pageTint: '#FFFAF5',
        glowPrimary: '#F3CBC2',
        glowSecondary: '#DDEAD2',
      },
      altText: 'A bright tortoiseshell cat with a green collar and a coral flower sprig.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 220,
    },
    {
      id: 'lantern-lane-cats:puddle',
      collectionId: 'lantern-lane-cats',
      name: 'Puddle',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A rain-loving explorer who knows the best reflections appear after a shower.',
      art: {
        classic: 'collectibles/puddle.svg',
        sticker: 'collectibles/puddle-sticker.webp',
      },
      theme: {
        accent: '#39708F',
        accentStrong: '#214A63',
        accentSoft: '#DFEFF6',
        pageTint: '#F8FBFC',
        glowPrimary: '#CEE6F0',
        glowSecondary: '#F6E3A7',
      },
      altText: 'A blue-gray cat with white paws, a yellow rain collar, and a raindrop charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 230,
    },
    {
      id: 'lantern-lane-cats:wick',
      collectionId: 'lantern-lane-cats',
      name: 'Wick',
      species: 'cat',
      specialGuest: false,
      rarity: 'common',
      description: 'A tiny lamplighter-in-training who takes every glowing window seriously.',
      art: {
        classic: 'collectibles/wick.svg',
        sticker: 'collectibles/wick-sticker.webp',
      },
      theme: {
        accent: '#95590F',
        accentStrong: '#5B3506',
        accentSoft: '#F7E6C5',
        pageTint: '#FBF8F2',
        glowPrimary: '#F2CE81',
        glowSecondary: '#D9D7ED',
      },
      altText: 'A small charcoal kitten with amber eyes and a glowing brass lantern charm.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 240,
    },
    {
      id: 'lantern-lane-cats:inkwell',
      collectionId: 'lantern-lane-cats',
      name: 'Inkwell',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A thoughtful bookbinder who gives well-loved stories a sturdy new beginning.',
      art: {
        classic: 'collectibles/inkwell.svg',
        sticker: 'collectibles/inkwell-sticker.webp',
      },
      theme: {
        accent: '#465A92',
        accentStrong: '#2B3961',
        accentSoft: '#E4E9F7',
        pageTint: '#FAFAFD',
        glowPrimary: '#D7DFF4',
        glowSecondary: '#E9D8C5',
      },
      altText: 'A neat tuxedo cat with indigo paws, round spectacles, and a small bound book.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 250,
    },
    {
      id: 'lantern-lane-cats:chime',
      collectionId: 'lantern-lane-cats',
      name: 'Chime',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A gentle clock-shop cat who hears a tiny melody in every passing hour.',
      art: {
        classic: 'collectibles/chime.svg',
        sticker: 'collectibles/chime-sticker.webp',
      },
      theme: {
        accent: '#70559A',
        accentStrong: '#493767',
        accentSoft: '#EEE7F8',
        pageTint: '#FCFAFF',
        glowPrimary: '#E1D7F2',
        glowSecondary: '#F1DCA9',
      },
      altText: 'A lilac-point cat with violet eyes, a blue collar, and a golden bell charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 260,
    },
    {
      id: 'lantern-lane-cats:maribel',
      collectionId: 'lantern-lane-cats',
      name: 'Maribel',
      species: 'cat',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A gracious theater usher who knows every good entrance begins with a welcome.',
      art: {
        classic: 'collectibles/maribel.svg',
        sticker: 'collectibles/maribel-sticker.webp',
      },
      theme: {
        accent: '#963D62',
        accentStrong: '#642541',
        accentSoft: '#F6E1EA',
        pageTint: '#FFF9FC',
        glowPrimary: '#EFCEDC',
        glowSecondary: '#F2DDB4',
      },
      altText: 'A cinnamon longhair cat with a plum bow and a gold theater-star charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 270,
    },
    {
      id: 'lantern-lane-cats:gable',
      collectionId: 'lantern-lane-cats',
      name: 'Gable',
      species: 'cat',
      specialGuest: false,
      rarity: 'rare',
      description: 'A sure-footed rooftop courier who can find a safe path above any busy street.',
      art: {
        classic: 'collectibles/gable.svg',
        sticker: 'collectibles/gable-sticker.webp',
      },
      theme: {
        accent: '#914B2C',
        accentStrong: '#5E301D',
        accentSoft: '#F5E2D6',
        pageTint: '#FCF9F5',
        glowPrimary: '#EBC7B2',
        glowSecondary: '#CFDFEA',
      },
      altText: 'A broad russet Maine Coon cat with a green scarf and a copper weather-vane charm.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 280,
    },
    {
      id: 'lantern-lane-cats:mosaic',
      collectionId: 'lantern-lane-cats',
      name: 'Mosaic',
      species: 'cat',
      specialGuest: false,
      rarity: 'rare',
      description: 'A stained-glass artist who catches ordinary light and sends it dancing.',
      art: {
        classic: 'collectibles/mosaic.svg',
        sticker: 'collectibles/mosaic-sticker.webp',
      },
      theme: {
        accent: '#356986',
        accentStrong: '#22465C',
        accentSoft: '#DDEEF4',
        pageTint: '#FAFCFC',
        glowPrimary: '#CDE4EC',
        glowSecondary: '#E7D6F0',
      },
      altText: 'A silver spotted cat with teal eyes and a colorful stained-glass collar piece.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 290,
    },
    {
      id: 'lantern-lane-cats:lumina',
      collectionId: 'lantern-lane-cats',
      name: 'Lumina',
      species: 'cat',
      specialGuest: false,
      rarity: 'legendary',
      description: 'The radiant keeper of Lantern Night, who makes sure every neighbor finds home.',
      art: {
        classic: 'collectibles/lumina.svg',
        sticker: 'collectibles/lumina-sticker.webp',
      },
      theme: {
        accent: '#8E5C10',
        accentStrong: '#593805',
        accentSoft: '#F8E8C1',
        pageTint: '#FBFAF5',
        glowPrimary: '#F2D17E',
        glowSecondary: '#D6D9F0',
      },
      altText: 'A regal white-and-gold longhair cat beneath an arch of glowing lanterns.',
      capsuleEligible: true,
      capsuleWeight: 4,
      shopEligible: true,
      shopPrice: 840,
      starterEligible: false,
      sortOrder: 299,
    },
  ],
} as const satisfies CollectionPack;
