import type { CollectionPack } from './types.ts';

export const NOOKSIDE_PUPS_PACK = {
  collection: {
    id: 'nookside-pups',
    name: 'Nookside Pups',
    description:
      'Ten good-hearted pups who turn every walk around Number Nook into a small adventure.',
    sortOrder: 20,
  },
  collectibles: [
    {
      id: 'nookside-pups:poppy',
      collectionId: 'nookside-pups',
      name: 'Poppy',
      species: 'dog',
      specialGuest: false,
      rarity: 'common',
      description: 'A friendly messenger who always has a little good news to deliver.',
      art: {
        classic: 'collectibles/poppy.svg',
        sticker: 'collectibles/poppy-sticker.webp',
      },
      theme: {
        accent: '#A53C2E',
        accentStrong: '#70251D',
        accentSoft: '#FFE5DE',
        pageTint: '#FFF9F2',
        glowPrimary: '#FFD3C8',
        glowSecondary: '#DDF2F0',
      },
      altText: 'A cheerful red-and-cream pup with upright ears and a messenger satchel.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 110,
    },
    {
      id: 'nookside-pups:waffles',
      collectionId: 'nookside-pups',
      name: 'Waffles',
      species: 'dog',
      specialGuest: false,
      rarity: 'common',
      description: 'A cozy host who believes every practice round deserves a good seat.',
      art: {
        classic: 'collectibles/waffles.svg',
        sticker: 'collectibles/waffles-sticker.webp',
      },
      theme: {
        accent: '#8A520C',
        accentStrong: '#5D3606',
        accentSoft: '#FFF0CF',
        pageTint: '#FFFAF0',
        glowPrimary: '#F8D99A',
        glowSecondary: '#E7E0FF',
      },
      altText: 'A fluffy golden pup wearing a purple checked game-night bandana.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 120,
    },
    {
      id: 'nookside-pups:scout',
      collectionId: 'nookside-pups',
      name: 'Scout',
      species: 'dog',
      specialGuest: false,
      rarity: 'common',
      description: 'A careful finder who notices the clues everyone else walks past.',
      art: {
        classic: 'collectibles/scout.svg',
        sticker: 'collectibles/scout-sticker.webp',
      },
      theme: {
        accent: '#286586',
        accentStrong: '#17445F',
        accentSoft: '#E2F1F8',
        pageTint: '#F9FCF8',
        glowPrimary: '#D2EAF3',
        glowSecondary: '#E2EDD2',
      },
      altText: 'A thoughtful tricolor pup with long ears and a leafy trail-marker collar.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 130,
    },
    {
      id: 'nookside-pups:dot',
      collectionId: 'nookside-pups',
      name: 'Dot',
      species: 'dog',
      specialGuest: false,
      rarity: 'common',
      description: 'A bouncy rhythm lover who turns the sidewalk into a game.',
      art: {
        classic: 'collectibles/dot.svg',
        sticker: 'collectibles/dot-sticker.webp',
      },
      theme: {
        accent: '#74409A',
        accentStrong: '#4D276C',
        accentSoft: '#F1E7FA',
        pageTint: '#FFFAF7',
        glowPrimary: '#E8D7F4',
        glowSecondary: '#D5F1EC',
      },
      altText: 'A lively white-and-charcoal spotted pup beside colorful chalk circles.',
      capsuleEligible: true,
      capsuleWeight: 60,
      shopEligible: true,
      shopPrice: 120,
      starterEligible: false,
      sortOrder: 140,
    },
    {
      id: 'nookside-pups:clover',
      collectionId: 'nookside-pups',
      name: 'Clover',
      species: 'dog',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A shaggy party planner who finds a reason to celebrate small wins.',
      art: {
        classic: 'collectibles/clover.svg',
        sticker: 'collectibles/clover-sticker.webp',
      },
      theme: {
        accent: '#39733E',
        accentStrong: '#244F29',
        accentSoft: '#E4F2DF',
        pageTint: '#FCFCF4',
        glowPrimary: '#D6EACD',
        glowSecondary: '#F5DBE4',
      },
      altText: 'A shaggy gray-and-cream pup with a green bow and clover garland.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 150,
    },
    {
      id: 'nookside-pups:mochi',
      collectionId: 'nookside-pups',
      name: 'Mochi',
      species: 'dog',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A calm companion who knows when a quiet break helps ideas settle.',
      art: {
        classic: 'collectibles/mochi.svg',
        sticker: 'collectibles/mochi-sticker.webp',
      },
      theme: {
        accent: '#A04425',
        accentStrong: '#6A2B17',
        accentSoft: '#F9E4D8',
        pageTint: '#FFF9F2',
        glowPrimary: '#F3D0BD',
        glowSecondary: '#D5ECE7',
      },
      altText: 'A calm russet-and-cream pup with a curled tail and a teal steam charm.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 160,
    },
    {
      id: 'nookside-pups:rollo',
      collectionId: 'nookside-pups',
      name: 'Rollo',
      species: 'dog',
      specialGuest: false,
      rarity: 'uncommon',
      description: 'A traveling storyteller who brings the little library wherever it is needed.',
      art: {
        classic: 'collectibles/rollo.svg',
        sticker: 'collectibles/rollo-sticker.webp',
      },
      theme: {
        accent: '#73502A',
        accentStrong: '#4C3218',
        accentSoft: '#F5E8D5',
        pageTint: '#FFFAF2',
        glowPrimary: '#EAD2B4',
        glowSecondary: '#D8ECE9',
      },
      altText: 'A long chocolate-and-tan pup with a golden bookmark scarf and an open book.',
      capsuleEligible: true,
      capsuleWeight: 25,
      shopEligible: true,
      shopPrice: 240,
      starterEligible: false,
      sortOrder: 170,
    },
    {
      id: 'nookside-pups:echo',
      collectionId: 'nookside-pups',
      name: 'Echo',
      species: 'dog',
      specialGuest: false,
      rarity: 'rare',
      description: 'A joyful musician who can turn a happy howl into a neighborhood song.',
      art: {
        classic: 'collectibles/echo.svg',
        sticker: 'collectibles/echo-sticker.webp',
      },
      theme: {
        accent: '#4258B0',
        accentStrong: '#293A7E',
        accentSoft: '#E6EAFF',
        pageTint: '#F9FAFF',
        glowPrimary: '#D6DEFF',
        glowSecondary: '#DDEFFD',
      },
      altText: 'A silver-and-blue husky-like pup with bright eyes and glowing sound ribbons.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 180,
    },
    {
      id: 'nookside-pups:velvet',
      collectionId: 'nookside-pups',
      name: 'Velvet',
      species: 'dog',
      specialGuest: false,
      rarity: 'rare',
      description: 'A graceful parade designer who gives every celebration one perfect flourish.',
      art: {
        classic: 'collectibles/velvet.svg',
        sticker: 'collectibles/velvet-sticker.webp',
      },
      theme: {
        accent: '#893667',
        accentStrong: '#5E2347',
        accentSoft: '#F8E4EF',
        pageTint: '#FFF9FC',
        glowPrimary: '#F0D2E3',
        glowSecondary: '#F5DDD0',
      },
      altText: 'A graceful cocoa poodle-like pup with a plum rosette and colorful ribbon.',
      capsuleEligible: true,
      capsuleWeight: 10,
      shopEligible: true,
      shopPrice: 480,
      starterEligible: false,
      sortOrder: 190,
    },
    {
      id: 'nookside-pups:beacon',
      collectionId: 'nookside-pups',
      name: 'Beacon',
      species: 'dog',
      specialGuest: false,
      rarity: 'legendary',
      description: 'A gentle night guide whose little lantern makes every path feel welcoming.',
      art: {
        classic: 'collectibles/beacon.svg',
        sticker: 'collectibles/beacon-sticker.webp',
      },
      theme: {
        accent: '#81521A',
        accentStrong: '#56350E',
        accentSoft: '#F7E9CD',
        pageTint: '#FBFAF5',
        glowPrimary: '#F3D89B',
        glowSecondary: '#D8E5E1',
      },
      altText: 'A large tricolor pup wearing a glowing brass lantern charm on an evening path.',
      capsuleEligible: true,
      capsuleWeight: 4,
      shopEligible: true,
      shopPrice: 840,
      starterEligible: false,
      sortOrder: 199,
    },
  ],
} as const satisfies CollectionPack;
