import type { CollectibleDefinition, CollectionDefinition } from '../schema.ts';
import type { CollectionPack } from './types.ts';

export interface PondsidePalDefinition extends CollectibleDefinition {
  artDirection: {
    signatureRead: string;
    palette: string;
    habitatElement: string;
  };
}

const collection = {
  id: 'pondside-pals',
  name: 'Pondside Pals',
  description:
    'Ten lively neighbors who make one bright pond ripple, hum, paddle, and shine from morning to moonlight.',
  sortOrder: 50,
} as const satisfies CollectionDefinition;

const collectibles = [
  {
    id: 'pondside-pals:moss',
    collectionId: 'pondside-pals',
    name: 'Moss',
    species: 'green-frog',
    specialGuest: false,
    rarity: 'common',
    description:
      'A bright green frog who listens carefully before making one wonderfully springy leap.',
    art: { classic: 'collectibles/moss.svg', sticker: 'collectibles/moss-sticker.webp' },
    theme: {
      accent: '#41713A',
      accentStrong: '#294A25',
      accentSoft: '#E2EFD9',
      pageTint: '#FBFCF4',
      glowPrimary: '#CAE5BE',
      glowSecondary: '#E8DCA7',
    },
    altText: 'A bright green frog crouched on a lily pad beside a small yellow pond flower.',
    capsuleEligible: true,
    capsuleWeight: 60,
    shopEligible: true,
    shopPrice: 120,
    starterEligible: false,
    sortOrder: 410,
    artDirection: {
      signatureRead: 'Wide frog eyes, folded legs, and a ready-to-hop pose',
      palette: 'Leaf green, moss, cream, and warm yellow',
      habitatElement: 'Lily pad with one small pond bloom',
    },
  },
  {
    id: 'pondside-pals:pebble',
    collectionId: 'pondside-pals',
    name: 'Pebble',
    species: 'painted-turtle',
    specialGuest: false,
    rarity: 'common',
    description:
      'A patient painted turtle who knows that steady paddles can cross the widest pond.',
    art: { classic: 'collectibles/pebble.svg', sticker: 'collectibles/pebble-sticker.webp' },
    theme: {
      accent: '#85513B',
      accentStrong: '#543126',
      accentSoft: '#F3E3D8',
      pageTint: '#FCFAF5',
      glowPrimary: '#E8CCB8',
      glowSecondary: '#CCE1C8',
    },
    altText: 'An olive painted turtle with a patterned shell resting on a smooth pond stone.',
    capsuleEligible: true,
    capsuleWeight: 60,
    shopEligible: true,
    shopPrice: 120,
    starterEligible: false,
    sortOrder: 420,
    artDirection: {
      signatureRead: 'Low turtle silhouette and patterned painted shell',
      palette: 'Olive, warm brown, amber, and small red markings',
      habitatElement: 'Smooth sunning stone near the waterline',
    },
  },
  {
    id: 'pondside-pals:skim',
    collectionId: 'pondside-pals',
    name: 'Skim',
    species: 'pond-skater',
    specialGuest: false,
    rarity: 'common',
    description:
      'A silly pond skater who zips across the surface without getting even one toe wet.',
    art: { classic: 'collectibles/skim.svg', sticker: 'collectibles/skim-sticker.webp' },
    theme: {
      accent: '#356C82',
      accentStrong: '#214758',
      accentSoft: '#DDEDF2',
      pageTint: '#F7FCFC',
      glowPrimary: '#C5E4EA',
      glowSecondary: '#E8E2B5',
    },
    altText: 'A smiling brown pond skater balancing on six long legs above circular ripples.',
    capsuleEligible: true,
    capsuleWeight: 60,
    shopEligible: true,
    shopPrice: 120,
    starterEligible: false,
    sortOrder: 430,
    artDirection: {
      signatureRead: 'Six long legs making visible dimples on the water',
      palette: 'Deep brown, cool blue, silver, and soft teal',
      habitatElement: 'Round surface ripples and a floating leaf',
    },
  },
  {
    id: 'pondside-pals:spiral',
    collectionId: 'pondside-pals',
    name: 'Spiral',
    species: 'pond-snail',
    specialGuest: false,
    rarity: 'common',
    description:
      'A thoughtful pond snail who always finds something interesting along the slow way around.',
    art: { classic: 'collectibles/spiral.svg', sticker: 'collectibles/spiral-sticker.webp' },
    theme: {
      accent: '#71567D',
      accentStrong: '#493752',
      accentSoft: '#EEE5F1',
      pageTint: '#FCFAFD',
      glowPrimary: '#DED0E5',
      glowSecondary: '#D3E5C9',
    },
    altText: 'A green pond snail with raised eye stalks and a large purple spiral shell.',
    capsuleEligible: true,
    capsuleWeight: 60,
    shopEligible: true,
    shopPrice: 120,
    starterEligible: false,
    sortOrder: 440,
    artDirection: {
      signatureRead: 'Large spiral shell, raised eye stalks, and tiny rippling foot',
      palette: 'Mulberry, soft lavender, moss green, and cream',
      habitatElement: 'Curled waterweed beside a smooth pebble',
    },
  },
  {
    id: 'pondside-pals:dabble',
    collectionId: 'pondside-pals',
    name: 'Dabble',
    species: 'mallard-duck',
    specialGuest: false,
    rarity: 'uncommon',
    description:
      'A cheerful mallard who is always dipping, paddling, and discovering what waits below.',
    art: { classic: 'collectibles/dabble.svg', sticker: 'collectibles/dabble-sticker.webp' },
    theme: {
      accent: '#2F6A61',
      accentStrong: '#1D463F',
      accentSoft: '#DCEDE8',
      pageTint: '#F7FCF9',
      glowPrimary: '#C5E3D9',
      glowSecondary: '#E8D6A9',
    },
    altText: 'A colorful mallard duck dabbling tail-up in teal pond water.',
    capsuleEligible: true,
    capsuleWeight: 25,
    shopEligible: true,
    shopPrice: 240,
    starterEligible: false,
    sortOrder: 450,
    artDirection: {
      signatureRead: 'Glossy green head, yellow bill, and dabbling tail-up pose',
      palette: 'Emerald, chestnut, cream, and golden yellow',
      habitatElement: 'Duckweed and a gently tipped water surface',
    },
  },
  {
    id: 'pondside-pals:glint',
    collectionId: 'pondside-pals',
    name: 'Glint',
    species: 'dragonfly',
    specialGuest: false,
    rarity: 'uncommon',
    description:
      'A sparkling dragonfly who turns every quick loop above the pond into a tiny show.',
    art: { classic: 'collectibles/glint.svg', sticker: 'collectibles/glint-sticker.webp' },
    theme: {
      accent: '#5D5795',
      accentStrong: '#3B3764',
      accentSoft: '#E9E7F6',
      pageTint: '#FAFBFE',
      glowPrimary: '#D7D4F2',
      glowSecondary: '#C6E8E0',
    },
    altText: 'An iridescent blue and violet dragonfly hovering with four transparent wings.',
    capsuleEligible: true,
    capsuleWeight: 25,
    shopEligible: true,
    shopPrice: 240,
    starterEligible: false,
    sortOrder: 460,
    artDirection: {
      signatureRead: 'Four transparent wings, long body, and hovering turn',
      palette: 'Iridescent blue, violet, teal, and pearl',
      habitatElement: 'Sunlit reeds with one reflected sparkle',
    },
  },
  {
    id: 'pondside-pals:willow',
    collectionId: 'pondside-pals',
    name: 'Willow',
    species: 'beaver',
    specialGuest: false,
    rarity: 'uncommon',
    description:
      'An inventive beaver who can turn a few good sticks into exactly what the pond needs.',
    art: { classic: 'collectibles/willow.svg', sticker: 'collectibles/willow-sticker.webp' },
    theme: {
      accent: '#705335',
      accentStrong: '#47341F',
      accentSoft: '#EFE4D6',
      pageTint: '#FCFAF5',
      glowPrimary: '#E2CCAF',
      glowSecondary: '#C8DFCF',
    },
    altText: 'A warm brown beaver building with sticks beside the pond, its broad tail visible.',
    capsuleEligible: true,
    capsuleWeight: 25,
    shopEligible: true,
    shopPrice: 240,
    starterEligible: false,
    sortOrder: 470,
    artDirection: {
      signatureRead: 'Broad paddle tail, rounded muzzle, and capable front paws',
      palette: 'Chestnut, cedar brown, tan, and willow green',
      habitatElement: 'Small woven stick bridge with willow leaves',
    },
  },
  {
    id: 'pondside-pals:ripple',
    collectionId: 'pondside-pals',
    name: 'Ripple',
    species: 'river-otter',
    specialGuest: false,
    rarity: 'rare',
    description:
      'A playful river otter who can turn one smooth swim into a whole afternoon of games.',
    art: { classic: 'collectibles/ripple.svg', sticker: 'collectibles/ripple-sticker.webp' },
    theme: {
      accent: '#386887',
      accentStrong: '#24455B',
      accentSoft: '#DFEBF2',
      pageTint: '#F7FBFD',
      glowPrimary: '#C8E1EE',
      glowSecondary: '#E7D6B8',
    },
    altText: 'A playful brown river otter curling through blue water beside a skipping stone.',
    capsuleEligible: true,
    capsuleWeight: 10,
    shopEligible: true,
    shopPrice: 480,
    starterEligible: false,
    sortOrder: 480,
    artDirection: {
      signatureRead: 'Long curved body, whiskered face, and playful swimming roll',
      palette: 'Chocolate brown, warm cream, river blue, and silver',
      habitatElement: 'Broad curling wake with one favorite skipping stone',
    },
  },
  {
    id: 'pondside-pals:lotus',
    collectionId: 'pondside-pals',
    name: 'Lotus',
    species: 'axolotl',
    specialGuest: false,
    rarity: 'rare',
    description: 'A gentle axolotl whose feathery gills flutter whenever a new idea drifts close.',
    art: { classic: 'collectibles/lotus.svg', sticker: 'collectibles/lotus-sticker.webp' },
    theme: {
      accent: '#98466C',
      accentStrong: '#642C47',
      accentSoft: '#F5E0E9',
      pageTint: '#FFF9FC',
      glowPrimary: '#EDC9DA',
      glowSecondary: '#CDE6E4',
    },
    altText: 'A smiling pink axolotl floating underwater with six coral feathery gills.',
    capsuleEligible: true,
    capsuleWeight: 10,
    shopEligible: true,
    shopPrice: 480,
    starterEligible: false,
    sortOrder: 490,
    artDirection: {
      signatureRead: 'Feathery external gills, broad smile, and floating aquatic pose',
      palette: 'Blush pink, coral, lavender, and clear aqua',
      habitatElement: 'Submerged lotus roots, bubbles, and soft water light',
    },
  },
  {
    id: 'pondside-pals:opal',
    collectionId: 'pondside-pals',
    name: 'Opal',
    species: 'koi',
    specialGuest: false,
    rarity: 'legendary',
    description:
      'A radiant koi who paints the pond with ribbons of color wherever the current leads.',
    art: { classic: 'collectibles/opal.svg', sticker: 'collectibles/opal-sticker.webp' },
    theme: {
      accent: '#654394',
      accentStrong: '#402961',
      accentSoft: '#ECE3F6',
      pageTint: '#FCF9FF',
      glowPrimary: '#DCCDF0',
      glowSecondary: '#F4D0AA',
    },
    altText: 'A radiant pearl, coral, and violet koi curving through opalescent pond light.',
    capsuleEligible: true,
    capsuleWeight: 4,
    shopEligible: true,
    shopPrice: 840,
    starterEligible: false,
    sortOrder: 500,
    artDirection: {
      signatureRead: 'Flowing fins, sweeping tail, and an elegant curved swimming pose',
      palette: 'Pearl white, coral, gold, violet, and opalescent blue',
      habitatElement: 'Moonlit ring of ripples with restrained rainbow reflections',
    },
  },
] as const satisfies readonly PondsidePalDefinition[];

export const PONDSIDE_PALS_PACK = {
  collection,
  collectibles,
} as const satisfies CollectionPack;
