import type { DialoguePhrase } from '../types.ts';

export const GARDEN_WINGLETS_SIGNATURE_PHRASES = [
  {
    id: 'tuck-home-01',
    context: 'home',
    text: 'I tucked a bright idea into this little nook for us.',
    companionIds: ['garden-winglets:tuck'],
  },
  {
    id: 'tuck-setup-01',
    context: 'setup',
    text: 'Let’s take this round one little climb at a time.',
    companionIds: ['garden-winglets:tuck'],
  },
  {
    id: 'tuck-results-01',
    context: 'results',
    text: 'You found your footing, even on the tricky parts.',
    companionIds: ['garden-winglets:tuck'],
  },
  {
    id: 'marigold-home-01',
    context: 'home',
    text: 'The garden sounds brighter with you here.',
    companionIds: ['garden-winglets:marigold'],
  },
  {
    id: 'marigold-setup-01',
    context: 'setup',
    text: 'Pick a challenge and I’ll bring the sunshine.',
    companionIds: ['garden-winglets:marigold'],
  },
  {
    id: 'marigold-results-01',
    context: 'results',
    text: 'That round opened up like a sunny flower!',
    companionIds: ['garden-winglets:marigold'],
  },
  {
    id: 'bluebell-home-01',
    context: 'home',
    text: 'I remember where we left every good idea.',
    companionIds: ['garden-winglets:bluebell'],
  },
  {
    id: 'bluebell-setup-01',
    context: 'setup',
    text: 'Let’s choose a puzzle path worth remembering.',
    companionIds: ['garden-winglets:bluebell'],
  },
  {
    id: 'bluebell-results-01',
    context: 'results',
    text: 'I’m tucking that clever round somewhere safe.',
    companionIds: ['garden-winglets:bluebell'],
  },
  {
    id: 'tumble-home-01',
    context: 'home',
    text: 'I found a tiny trail that leads right to practice.',
    companionIds: ['garden-winglets:tumble'],
  },
  {
    id: 'tumble-setup-01',
    context: 'setup',
    text: 'Small steps can cover a surprising bit of ground!',
    companionIds: ['garden-winglets:tumble'],
  },
  {
    id: 'tumble-results-01',
    context: 'results',
    text: 'Look at all those neat little steps behind us!',
    companionIds: ['garden-winglets:tumble'],
  },
  {
    id: 'zinnia-home-01',
    context: 'home',
    text: 'I zipped over as soon as I saw you!',
    companionIds: ['garden-winglets:zinnia'],
  },
  {
    id: 'zinnia-setup-01',
    context: 'setup',
    text: 'Choose our next flower—I mean, challenge!',
    companionIds: ['garden-winglets:zinnia'],
  },
  {
    id: 'zinnia-results-01',
    context: 'results',
    text: 'That round had plenty of bright little moments.',
    companionIds: ['garden-winglets:zinnia'],
  },
  {
    id: 'bramble-home-01',
    context: 'home',
    text: 'I found a cozy branch with room for two.',
    companionIds: ['garden-winglets:bramble'],
  },
  {
    id: 'bramble-setup-01',
    context: 'setup',
    text: 'Take your pick. We can make any challenge feel friendly.',
    companionIds: ['garden-winglets:bramble'],
  },
  {
    id: 'bramble-results-01',
    context: 'results',
    text: 'A good round is sweeter when we share it.',
    companionIds: ['garden-winglets:bramble'],
  },
  {
    id: 'fern-home-01',
    context: 'home',
    text: 'I inspected the Nook. Everything is ready!',
    companionIds: ['garden-winglets:fern'],
  },
  {
    id: 'fern-setup-01',
    context: 'setup',
    text: 'Let’s find the shape that helps this round grow.',
    companionIds: ['garden-winglets:fern'],
  },
  {
    id: 'fern-results-01',
    context: 'results',
    text: 'Those ideas climbed higher than a garden vine.',
    companionIds: ['garden-winglets:fern'],
  },
  {
    id: 'tempo-home-01',
    context: 'home',
    text: 'I tapped out a cheerful welcome just for you.',
    companionIds: ['garden-winglets:tempo'],
  },
  {
    id: 'tempo-setup-01',
    context: 'setup',
    text: 'Every kind of challenge can find its own rhythm.',
    companionIds: ['garden-winglets:tempo'],
  },
  {
    id: 'tempo-results-01',
    context: 'results',
    text: 'That whole round found a wonderful rhythm.',
    companionIds: ['garden-winglets:tempo'],
  },
  {
    id: 'prism-home-01',
    context: 'home',
    text: 'I spotted something sparkling just ahead.',
    companionIds: ['garden-winglets:prism'],
  },
  {
    id: 'prism-setup-01',
    context: 'setup',
    text: 'Pick a challenge and we’ll dive right in.',
    companionIds: ['garden-winglets:prism'],
  },
  {
    id: 'prism-results-01',
    context: 'results',
    text: 'Every careful answer made a little ripple.',
    companionIds: ['garden-winglets:prism'],
  },
  {
    id: 'solstice-home-01',
    context: 'home',
    text: 'You arrived just in time to brighten the garden.',
    companionIds: ['garden-winglets:solstice'],
  },
  {
    id: 'solstice-setup-01',
    context: 'setup',
    text: 'Let’s choose where today’s bright flight begins.',
    companionIds: ['garden-winglets:solstice'],
  },
  {
    id: 'solstice-results-01',
    context: 'results',
    text: 'You gave that whole round a wonderful glow.',
    companionIds: ['garden-winglets:solstice'],
  },
] as const satisfies readonly DialoguePhrase[];
