import type { DialoguePhrase } from '../types.ts';

export const LANTERN_LANE_CATS_SIGNATURE_PHRASES = [
  {
    id: 'crumpet-home-01',
    context: 'home',
    text: 'Your warm seat is ready.',
    companionIds: ['lantern-lane-cats:crumpet'],
  },
  {
    id: 'crumpet-setup-01',
    context: 'setup',
    text: 'Let’s settle in with a cozy challenge.',
    companionIds: ['lantern-lane-cats:crumpet'],
  },
  {
    id: 'crumpet-results-01',
    context: 'results',
    text: 'That round deserves the window seat!',
    companionIds: ['lantern-lane-cats:crumpet'],
  },
  {
    id: 'tansy-home-01',
    context: 'home',
    text: 'I found a bright little spot for today.',
    companionIds: ['lantern-lane-cats:tansy'],
  },
  {
    id: 'tansy-setup-01',
    context: 'setup',
    text: 'Pick a challenge and we’ll help it bloom.',
    companionIds: ['lantern-lane-cats:tansy'],
  },
  {
    id: 'tansy-results-01',
    context: 'results',
    text: 'Every answer added a little color.',
    companionIds: ['lantern-lane-cats:tansy'],
  },
  {
    id: 'puddle-home-01',
    context: 'home',
    text: 'The lane looks extra shiny today.',
    companionIds: ['lantern-lane-cats:puddle'],
  },
  {
    id: 'puddle-setup-01',
    context: 'setup',
    text: 'Let’s splash into whichever round looks fun.',
    companionIds: ['lantern-lane-cats:puddle'],
  },
  {
    id: 'puddle-results-01',
    context: 'results',
    text: 'That practice left some lovely ripples.',
    companionIds: ['lantern-lane-cats:puddle'],
  },
  {
    id: 'wick-home-01',
    context: 'home',
    text: 'I lit the smallest lamp just for you.',
    companionIds: ['lantern-lane-cats:wick'],
  },
  {
    id: 'wick-setup-01',
    context: 'setup',
    text: 'One bright question at a time!',
    companionIds: ['lantern-lane-cats:wick'],
  },
  {
    id: 'wick-results-01',
    context: 'results',
    text: 'Look how much brighter the lane feels now.',
    companionIds: ['lantern-lane-cats:wick'],
  },
  {
    id: 'inkwell-home-01',
    context: 'home',
    text: 'There’s room for one more good page.',
    companionIds: ['lantern-lane-cats:inkwell'],
  },
  {
    id: 'inkwell-setup-01',
    context: 'setup',
    text: 'Let’s choose the next part carefully.',
    companionIds: ['lantern-lane-cats:inkwell'],
  },
  {
    id: 'inkwell-results-01',
    context: 'results',
    text: 'That round fits nicely into today’s story.',
    companionIds: ['lantern-lane-cats:inkwell'],
  },
  {
    id: 'chime-home-01',
    context: 'home',
    text: 'The lane is humming a welcome tune.',
    companionIds: ['lantern-lane-cats:chime'],
  },
  {
    id: 'chime-setup-01',
    context: 'setup',
    text: 'We can find a gentle rhythm for this round.',
    companionIds: ['lantern-lane-cats:chime'],
  },
  {
    id: 'chime-results-01',
    context: 'results',
    text: 'That practice ended on a lovely note.',
    companionIds: ['lantern-lane-cats:chime'],
  },
  {
    id: 'maribel-home-01',
    context: 'home',
    text: 'Right this way—your favorite spot is ready.',
    companionIds: ['lantern-lane-cats:maribel'],
  },
  {
    id: 'maribel-setup-01',
    context: 'setup',
    text: 'Choose a round and we’ll make a fine entrance.',
    companionIds: ['lantern-lane-cats:maribel'],
  },
  {
    id: 'maribel-results-01',
    context: 'results',
    text: 'What a lovely finish. Take a little bow!',
    companionIds: ['lantern-lane-cats:maribel'],
  },
  {
    id: 'gable-home-01',
    context: 'home',
    text: 'I found us a clear path across the rooftops.',
    companionIds: ['lantern-lane-cats:gable'],
  },
  {
    id: 'gable-setup-01',
    context: 'setup',
    text: 'Pick a destination and we’ll find the sure steps.',
    companionIds: ['lantern-lane-cats:gable'],
  },
  {
    id: 'gable-results-01',
    context: 'results',
    text: 'You made steady steps all the way across.',
    companionIds: ['lantern-lane-cats:gable'],
  },
  {
    id: 'mosaic-home-01',
    context: 'home',
    text: 'The window light saved some colors for us.',
    companionIds: ['lantern-lane-cats:mosaic'],
  },
  {
    id: 'mosaic-setup-01',
    context: 'setup',
    text: 'Let’s turn this challenge toward the light.',
    companionIds: ['lantern-lane-cats:mosaic'],
  },
  {
    id: 'mosaic-results-01',
    context: 'results',
    text: 'That effort sent bright colors everywhere.',
    companionIds: ['lantern-lane-cats:mosaic'],
  },
  {
    id: 'lumina-home-01',
    context: 'home',
    text: 'Every lantern on the lane is glad you’re here.',
    companionIds: ['lantern-lane-cats:lumina'],
  },
  {
    id: 'lumina-setup-01',
    context: 'setup',
    text: 'Choose your path. I’ll keep the lanterns glowing.',
    companionIds: ['lantern-lane-cats:lumina'],
  },
  {
    id: 'lumina-results-01',
    context: 'results',
    text: 'Your practice gave Lantern Lane a beautiful glow.',
    companionIds: ['lantern-lane-cats:lumina'],
  },
] as const satisfies readonly DialoguePhrase[];
