import type { DialoguePhrase } from '../types.ts';

export const NOOKSIDE_PUPS_SIGNATURE_PHRASES = [
  {
    id: 'poppy-home-01',
    context: 'home',
    text: 'I saved a little hello for you.',
    companionIds: ['nookside-pups:poppy'],
  },
  {
    id: 'poppy-setup-01',
    context: 'setup',
    text: 'Let’s carry this practice one step at a time.',
    companionIds: ['nookside-pups:poppy'],
  },
  {
    id: 'poppy-results-01',
    context: 'results',
    text: 'Good news: you brought some lovely practice to the Nook!',
    companionIds: ['nookside-pups:poppy'],
  },
  {
    id: 'waffles-home-01',
    context: 'home',
    text: 'I kept the coziest spot open for you.',
    companionIds: ['nookside-pups:waffles'],
  },
  {
    id: 'waffles-setup-01',
    context: 'setup',
    text: 'We can take this round at your pace.',
    companionIds: ['nookside-pups:waffles'],
  },
  {
    id: 'waffles-results-01',
    context: 'results',
    text: 'That was a fine round for game night!',
    companionIds: ['nookside-pups:waffles'],
  },
  {
    id: 'scout-home-01',
    context: 'home',
    text: 'I noticed a good path from here.',
    companionIds: ['nookside-pups:scout'],
  },
  {
    id: 'scout-setup-01',
    context: 'setup',
    text: 'Let’s follow this challenge wherever it goes.',
    companionIds: ['nookside-pups:scout'],
  },
  {
    id: 'scout-results-01',
    context: 'results',
    text: 'A careful look found a lot in that round.',
    companionIds: ['nookside-pups:scout'],
  },
  {
    id: 'dot-home-01',
    context: 'home',
    text: 'I found a fun rhythm for today.',
    companionIds: ['nookside-pups:dot'],
  },
  {
    id: 'dot-setup-01',
    context: 'setup',
    text: 'Hop into whichever challenge looks fun!',
    companionIds: ['nookside-pups:dot'],
  },
  {
    id: 'dot-results-01',
    context: 'results',
    text: 'That round had a pretty good bounce to it!',
    companionIds: ['nookside-pups:dot'],
  },
  {
    id: 'clover-home-01',
    context: 'home',
    text: 'I brought an extra bit of good luck.',
    companionIds: ['nookside-pups:clover'],
  },
  {
    id: 'clover-setup-01',
    context: 'setup',
    text: 'Let’s pick something worth celebrating.',
    companionIds: ['nookside-pups:clover'],
  },
  {
    id: 'clover-results-01',
    context: 'results',
    text: 'Little wins make lovely decorations.',
    companionIds: ['nookside-pups:clover'],
  },
  {
    id: 'mochi-home-01',
    context: 'home',
    text: 'We have plenty of room to think.',
    companionIds: ['nookside-pups:mochi'],
  },
  {
    id: 'mochi-setup-01',
    context: 'setup',
    text: 'Let’s settle in and see what you discover.',
    companionIds: ['nookside-pups:mochi'],
  },
  {
    id: 'mochi-results-01',
    context: 'results',
    text: 'Those ideas had time to settle in nicely.',
    companionIds: ['nookside-pups:mochi'],
  },
  {
    id: 'rollo-home-01',
    context: 'home',
    text: 'This feels like the start of a good chapter.',
    companionIds: ['nookside-pups:rollo'],
  },
  {
    id: 'rollo-setup-01',
    context: 'setup',
    text: 'Let’s see what happens on the next page.',
    companionIds: ['nookside-pups:rollo'],
  },
  {
    id: 'rollo-results-01',
    context: 'results',
    text: 'That round belongs in the good chapter.',
    companionIds: ['nookside-pups:rollo'],
  },
  {
    id: 'echo-home-01',
    context: 'home',
    text: 'I like the sound of another round.',
    companionIds: ['nookside-pups:echo'],
  },
  {
    id: 'echo-setup-01',
    context: 'setup',
    text: 'Let’s find today’s rhythm together.',
    companionIds: ['nookside-pups:echo'],
  },
  {
    id: 'echo-results-01',
    context: 'results',
    text: 'That practice made a bright little song.',
    companionIds: ['nookside-pups:echo'],
  },
  {
    id: 'velvet-home-01',
    context: 'home',
    text: 'I saved the grand ribbon for just the right moment.',
    companionIds: ['nookside-pups:velvet'],
  },
  {
    id: 'velvet-setup-01',
    context: 'setup',
    text: 'Let’s give this challenge one perfect flourish.',
    companionIds: ['nookside-pups:velvet'],
  },
  {
    id: 'velvet-results-01',
    context: 'results',
    text: 'Every good effort deserves a little flourish.',
    companionIds: ['nookside-pups:velvet'],
  },
  {
    id: 'beacon-home-01',
    context: 'home',
    text: 'I’ll keep a warm light on for you.',
    companionIds: ['nookside-pups:beacon'],
  },
  {
    id: 'beacon-setup-01',
    context: 'setup',
    text: 'We can find our way one question at a time.',
    companionIds: ['nookside-pups:beacon'],
  },
  {
    id: 'beacon-results-01',
    context: 'results',
    text: 'No path feels quite so long with company.',
    companionIds: ['nookside-pups:beacon'],
  },
] as const satisfies readonly DialoguePhrase[];
