import type { DialoguePhrase } from '../types.ts';

export const PONDSIDE_PALS_SIGNATURE_PHRASES = [
  {
    id: 'moss-home-01',
    context: 'home',
    text: 'I found us a quiet lily pad with room for a bright idea.',
    companionIds: ['pondside-pals:moss'],
  },
  {
    id: 'moss-setup-01',
    context: 'setup',
    text: 'Let’s listen, look, and leap into the challenge that feels right.',
    companionIds: ['pondside-pals:moss'],
  },
  {
    id: 'moss-results-01',
    context: 'results',
    text: 'That round was worth the leap!',
    companionIds: ['pondside-pals:moss'],
  },
  {
    id: 'pebble-home-01',
    context: 'home',
    text: 'The warmest sunning stone is ready for you.',
    companionIds: ['pondside-pals:pebble'],
  },
  {
    id: 'pebble-setup-01',
    context: 'setup',
    text: 'Pick a path and we’ll paddle through it steadily.',
    companionIds: ['pondside-pals:pebble'],
  },
  {
    id: 'pebble-results-01',
    context: 'results',
    text: 'Steady practice carried us all the way across.',
    companionIds: ['pondside-pals:pebble'],
  },
  {
    id: 'skim-home-01',
    context: 'home',
    text: 'The water is smooth, and I am ready to scoot!',
    companionIds: ['pondside-pals:skim'],
  },
  {
    id: 'skim-setup-01',
    context: 'setup',
    text: 'Choose a challenge and we’ll zip right over.',
    companionIds: ['pondside-pals:skim'],
  },
  {
    id: 'skim-results-01',
    context: 'results',
    text: 'Look at all those little ripples we made!',
    companionIds: ['pondside-pals:skim'],
  },
  {
    id: 'spiral-home-01',
    context: 'home',
    text: 'I took the scenic route and saved the best bit for us.',
    companionIds: ['pondside-pals:spiral'],
  },
  {
    id: 'spiral-setup-01',
    context: 'setup',
    text: 'No hurry. Let’s choose a challenge worth noticing.',
    companionIds: ['pondside-pals:spiral'],
  },
  {
    id: 'spiral-results-01',
    context: 'results',
    text: 'Slow or speedy, every answer moved us forward.',
    companionIds: ['pondside-pals:spiral'],
  },
  {
    id: 'dabble-home-01',
    context: 'home',
    text: 'I spotted something interesting just below the surface.',
    companionIds: ['pondside-pals:dabble'],
  },
  {
    id: 'dabble-setup-01',
    context: 'setup',
    text: 'Pick a round and we’ll dabble our way in!',
    companionIds: ['pondside-pals:dabble'],
  },
  {
    id: 'dabble-results-01',
    context: 'results',
    text: 'That practice gave the whole pond something to quack about.',
    companionIds: ['pondside-pals:dabble'],
  },
  {
    id: 'glint-home-01',
    context: 'home',
    text: 'The sunshine left a little sparkle here for us.',
    companionIds: ['pondside-pals:glint'],
  },
  {
    id: 'glint-setup-01',
    context: 'setup',
    text: 'Choose our next loop around the pond.',
    companionIds: ['pondside-pals:glint'],
  },
  {
    id: 'glint-results-01',
    context: 'results',
    text: 'That round flashed by with some brilliant moments.',
    companionIds: ['pondside-pals:glint'],
  },
  {
    id: 'willow-home-01',
    context: 'home',
    text: 'I brought a few sticks in case we want to build an idea.',
    companionIds: ['pondside-pals:willow'],
  },
  {
    id: 'willow-setup-01',
    context: 'setup',
    text: 'Let’s choose the pieces and build this round together.',
    companionIds: ['pondside-pals:willow'],
  },
  {
    id: 'willow-results-01',
    context: 'results',
    text: 'Every answer helped that practice hold together.',
    companionIds: ['pondside-pals:willow'],
  },
  {
    id: 'ripple-home-01',
    context: 'home',
    text: 'I saved the smoothest skipping stone for you.',
    companionIds: ['pondside-pals:ripple'],
  },
  {
    id: 'ripple-setup-01',
    context: 'setup',
    text: 'Pick a challenge and we’ll roll right into it.',
    companionIds: ['pondside-pals:ripple'],
  },
  {
    id: 'ripple-results-01',
    context: 'results',
    text: 'That round turned into a very good splash!',
    companionIds: ['pondside-pals:ripple'],
  },
  {
    id: 'lotus-home-01',
    context: 'home',
    text: 'A new idea floated past, so I kept it safe for you.',
    companionIds: ['pondside-pals:lotus'],
  },
  {
    id: 'lotus-setup-01',
    context: 'setup',
    text: 'Let’s choose a challenge and see where it drifts.',
    companionIds: ['pondside-pals:lotus'],
  },
  {
    id: 'lotus-results-01',
    context: 'results',
    text: 'Your bright ideas made the water shimmer.',
    companionIds: ['pondside-pals:lotus'],
  },
  {
    id: 'opal-home-01',
    context: 'home',
    text: 'The pond saved its brightest colors for your return.',
    companionIds: ['pondside-pals:opal'],
  },
  {
    id: 'opal-setup-01',
    context: 'setup',
    text: 'Choose a current, and we’ll follow it into something wonderful.',
    companionIds: ['pondside-pals:opal'],
  },
  {
    id: 'opal-results-01',
    context: 'results',
    text: 'That practice painted beautiful colors across the pond.',
    companionIds: ['pondside-pals:opal'],
  },
] as const satisfies readonly DialoguePhrase[];
